{
  "headers": {
    "cache-control": "no-cache",
    "postman-token": "fa391e8e-92dd-4c25-84d0-b563283cddb4",
    "content-type": "application/json",
    "content-length": "116",
    "host": "localhost:8085",
    "user-agent": "PostmanRuntime/2.5.0",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "authorization": "Bearer eyJhbGciOiAiSFMyNTYiLCJ0eXAiOiAiSldUIn0.eyJ1c2VySWQiOiAiQi00Njc4ODQiLCJpc3MiOiAiZWNvbW1lcmNlX3N1aXRlX2JhY2tlbmQiLCJhdWQiOiAiZWNvbW1lcmNlX2FwaSIsImlhdCI6IDE3ODg3OTc3ODYsImV4cCI6IDE3ODg4MDEzODYsInJvbGUiOiAiYnV5ZXIifQ.2DQZpbRbJ3TEPCmNfGxxsnc6_ZMK3ofX7xS8l-75zIs"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/exp/orders",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/orders",
  "listenerPath": "/exp/*",
  "localAddress": "/127.0.0.1:8085",
  "relativePath": "/exp/orders",
  "uriParams": {},
  "rawRequestUri": "/exp/orders",
  "rawRequestPath": "/exp/orders",
  "remoteAddress": "/127.0.0.1:55760",
  "requestPath": "/exp/orders"
}