{
  "headers": {
    "content-type": "application/json",
    "authorization": "Bearer eyJhbGciOiAiSFMyNTYiLCJ0eXAiOiAiSldUIn0.eyJ1c2VySWQiOiAiQi1kYzRjMjUiLCJpc3MiOiAiZWNvbW1lcmNlX3N1aXRlX2JhY2tlbmQiLCJhdWQiOiAiZWNvbW1lcmNlX2FwaSIsImlhdCI6IDE3ODY5MzE3ODYsImV4cCI6IDE3ODY5MzUzODYsInJvbGUiOiAiYnV5ZXIifQ.P0-9aavUtTCTH2vuypOyervy_AxUKjlCptKZoD5igi8",
    "user-agent": "PostmanRuntime/7.56.1",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "c5835df2-cf6f-4cf3-8917-f6297586c01f",
    "host": "localhost:8085",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "49"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/exp/carts",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/carts",
  "listenerPath": "/exp/*",
  "localAddress": "/127.0.0.1:8085",
  "relativePath": "/exp/carts",
  "uriParams": {},
  "rawRequestUri": "/exp/carts",
  "rawRequestPath": "/exp/carts",
  "remoteAddress": "/127.0.0.1:65230",
  "requestPath": "/exp/carts"
}