{
  "headers": {
    "cache-control": "no-cache",
    "postman-token": "6227efbb-622b-4b41-ac23-cb5acac0094c",
    "content-type": "application/json",
    "content-length": "49",
    "host": "localhost:8085",
    "user-agent": "PostmanRuntime/2.5.0",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "authorization": "Bearer eyJhbGciOiAiSFMyNTYiLCJ0eXAiOiAiSldUIn0.eyJ1c2VySWQiOiAiQi00Njc4ODQiLCJpc3MiOiAiZWNvbW1lcmNlX3N1aXRlX2JhY2tlbmQiLCJhdWQiOiAiZWNvbW1lcmNlX2FwaSIsImlhdCI6IDE3ODg5MzIyMTYsImV4cCI6IDE3ODg5MzU4MTYsInJvbGUiOiAiYnV5ZXIifQ.IB_qovuLD8P4mirP0Vq5rZXewnjvFxv3Qta6kDuoq54"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/exp/carts",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/carts",
  "listenerPath": "/exp/*",
  "localAddress": "/127.0.0.1:8085",
  "relativePath": "/exp/carts",
  "uriParams": {},
  "rawRequestUri": "/exp/carts",
  "rawRequestPath": "/exp/carts",
  "remoteAddress": "/127.0.0.1:60404",
  "requestPath": "/exp/carts"
}