name: Test Experience API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Munit tests
        run: mvn mule:deploy -Dmule.artifact=deployment/ecommerce_suite_experience_api-1.0.0-SNAPSHOT-mule-application.jar
        env:
          connectedAppClientId: ${{ secrets.anypoint_connected_apps_client_id }}
          connectedAppClientSecret: ${{ secrets.anypoint_connected_apps_client_secret }}
